version: '3.8'
services:
  traefik:
    image: "traefik:v3.0"
    command:
      - "--configFile=/traefik.yml"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./traefik.yml:/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"
  web:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.routers.web.entrypoints=web"